name: immich_flutter_app
description: A Flutter app that connects to Immich API and displays pictures
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  crypto: ^3.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true 